### ISSUE TITLE
[i18n] Package requires Servicemanager but is mentioned as optional in the composer.json

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-i18n#50]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7547
User: @mvriel
Created On: 2015-05-25T07:00:20Z
Updated At: 2015-11-06T21:53:39Z
Body
When I want to use the I18n component provided by Zend Framework I am required to also add Zend Servicemanager but that is not listed as a "required" dependency but rather as a suggestion.

I would prefer not to install the Servicemanager (I have no use for it) but at the least it should be in the "required" section of the composer.json

---

**Comment by sbarre** [comment]
Has anyone figured out a solution for this?  Should I just install the ServiceManager?

**Comment by weierophinney** [comment]
@sbarre there's nothing to solve.

The reason zend-servicemanager is not marked as required is because requirements will be based on what aspects of the component you consume.
- If you are only consuming the filters, you will want to install zend-filter.
- If you are only consuming the validators, you will want to install zend-validator.
- If you are using the translator and/or related view helpers, you will need zend-servicemanager, and potentially zend-eventmanager and zend-cache.

Dependencies will be based on _what you consume_. So, yes, if you are using the translator, you will need to install zend-servicemanager as well, if you are not already.

**Comment by sbarre** [comment]
Thanks for the clarification, I didn't consider the fact that one could use this without the translator.
